export const ActionTypes = {
  ADD_NEW_PRODUCT: "ADD_NEW_PRODUCT",
  UPDATE_PRODUCT: "UPDATE_PRODUCT",
  SET_SELECTED_PRODUCT: "SET_SELECTED_PRODUCT",
  SET_PRODUCTS: "SET_PRODUCTS",
  SORT_PRODUCTS_BY_NAME: "SORT_PRODUCTS_BY_NAME",
  SORT_PRODUCTS_BY_CATEGORY: "SORT_PRODUCTS_BY_CATEGORY",

  ADD_NEW_CATEGORY: "ADD_NEW_CATEGORY",
  UPDATE_CATEGORY: "UPDATE_PRODUCT",
  SET_SELECTED_CATEGORY: "SET_SELECTED_CATEGORY",
  SET_CATEGORIES: "SET_CATEGORIES",
};
